CREATE DATABASE colleges;
USE college;
CREATE TABLE IF NOT EXISTS  students (
id int PRIMARY KEY, #PRIMARY KEY -
name VARCHAR(50), #strng type data {a,v,c,d....}
age INT NOT NULL # AGE CANT BE 0 AS USER WILL HAVE ATLEAST SOME AGE THEREFORE USED NOT NULL
);

INSERT INTO students VALUES(1,"PRATYKSH",20);
INSERT INTO students VALUES(2,"KRISH",20);
INSERT INTO students VALUES(3,"AARAV",20);
INSERT INTO students VALUES(4,"NIKHIL",20);
INSERT INTO students VALUES(5,"ROBBY",20);
#HERE IF id ARE SAME WE WILL GET ERROR AS IDS CANT BE SAME AND PRIMARY KEY IS USED FOR IT 

SELECT * FROM students; #TO PRINT THE TABLE