#SQL COMMANDS
#DDL - DATA DEFINATION LANGUAGE : CREATE , ALTER , RENAME , DROP , TRUNCATE
#DQL - DATA QUERY LANGUAGE : SELECT
#DML - DATA MANIPULATION LANGUAGE : INSERT , UPDATE AND DELETE
#DCL - DATA CONTROL LANGUAGE : GRANT AND REVOKE PERMISSION TO USERS
#TCL - START TRANSITION , COMMIT , ROLLBACK 